// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqanisnpgfgrxnlvpqss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxYW5pc25wZ2ZncnhubHZwcXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxNjYwNjIsImV4cCI6MjA1MTc0MjA2Mn0.4Wqh6H612Kl4whCLeJKvnCBpAEz--IAuaoVi00RSuQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);